language: node_js
dist: trusty
sudo: required
node_js: stable
install:
  - npm install -g bower@^1.8.8 purescript@^0.13.0 pulp@^13.0.0 spago@^0.8.3
  - spago install
  - bower install
script:
  - spago build
  - spago test
  - rm -rf .spago output
  - pulp build
